### ISSUE TITLE
[130s-runiq] Things can be fixed for Android Wear integration with New Balance watch

### ISSUE THREAD

**Issue by 130s** [130s/hut_10sqft#201]
- [x] Keeps discharging while on the charging dock (now it's 47% charged while it's sitting for a day) -> done https://github.com/130s/hut_10sqft/issues/201#issuecomment-347526665
- [x] Role of 3 buttons? -> https://github.com/130s/hut_10sqft/issues/201#issuecomment-373982371
- [x] Basic tutorial for listening to audio contents -> https://runiq.newbalance.com/hc/en-us/articles/115000358007-Google-Play-Music-with-Android-Wear-2-0 -> https://github.com/130s/hut_10sqft/issues/201#issuecomment-373982444
- [x] Unclear how to track runs, with heart rate recorded -> https://github.com/130s/hut_10sqft/issues/201#issuecomment-373982480
- [x] How to turn off the screen when unnecessary. -> https://github.com/130s/hut_10sqft/issues/201#issuecomment-373981991
- [x] On the charging dock, the screen keeps flipping 45 degree endlessly -> https://github.com/130s/hut_10sqft/issues/201#issuecomment-373982082
- [x] Need a charging dock -> done https://github.com/130s/hut_10sqft/issues/201#issuecomment-347528037
- [x] Android Wear not finding a watch that got removed from the list -> done https://github.com/130s/hut_10sqft/issues/259
- [x] RunIQ disconnects so often, say once in a few days. Once this happens, no way other than waiting to re-connect. -> Done https://github.com/130s/hut_10sqft/issues/201#issuecomment-369468045

**Comment by 130s** [comment]
- [ ] Basic tutorial for listening to audio contents -> https://runiq.newbalance.com/hc/en-us/articles/115000358007-Google-Play-Music-with-Android-Wear-2-0

**Comment by 130s** [comment]
- [ ] Unclear how to track runs, with heart rate recorded

**Comment by 130s** [comment]
- [ ] How to turn off the screen when unnecessary. 
- [ ] On the charging dock, the screen keeps flipping 45 degree englessly

**Comment by 130s** [comment]
> - [ ]  Keeps discharging while on the charging dock (now it's 47% charged while it's sitting for a day)

I haven't seen this for awhile. Maybe it's related to whether watt provision is sufficient or not, since this was only observed when connected to a PC (serval) that I've also seen other devices not charged really well.

**Comment by 130s** [comment]
- [x] Need a charging dock
  Now that I decided to not return the watch, I want another charging docks.
  - [x] [Made by Artifex](https://www.amazon.com/Balance-Artifex-Charging-Technology-Smartwatch/dp/B06XDTGL1F). Only $10, no review yet on Amazon. The maker's review looks to be ok [here](https://www.ebay.com/itm/New-Balance-RUN-IQ-Watch-Stand-Artifex-Charging-Dock-Stand-for-RUNIQ-/222437642748?nav=SEARCH). Give it a try.
  - [Genuine product by NewBalance](http://www.newbalance.com/pd/nb-runiq-charger-set/UA63101.html#color=Black&size=OSFA) $25 by just a dock! No-no.

**Comment by 130s** [comment]
- Android Wear not finding a watch that got removed from the list

I started having a connection issue on my RunIQ so removed it from the Android Wear app on the phone then it never finds again. On the Watch's Bluetooth view, the phone's name is still listed and I can't find how I can delete it.

**Comment by 130s** [comment]
> - [ ] RunIQ disconnects so often, say once in a few days. Once this happens, no way other than waiting to re-connect.

I found re-starting the watch helped.

**Comment by 130s** [comment]
> -  How to turn off the screen when unnecessary.

In System setting there's an option to turn off display.

**Comment by 130s** [comment]
> - [x] On the charging dock, the screen keeps flipping 45 degree endlessly

Tilt the phone enough. Using [a dock like this](https://www.amazon.com/dp/B06XDTGL1F/ref=cm_cr_ryp_prd_ttl_sol_0) helps.

**Comment by 130s** [comment]
> - [ ]  Role of 3 buttons?

[Summary](https://runiq.newbalance.com/hc/en-us/articles/235479488-Button-Functionality-Dashboard-Information). Looks like run specific feature is there.

**Comment by 130s** [comment]
> - [ ] Basic tutorial for listening to audio contents 

No need. I'll probably always carry a phone even when jogging.

**Comment by 130s** [comment]
> - [ ]  Unclear how to track runs, with heart rate recorded

Let's see how `Strava` works for my purpose.
