### ISSUE TITLE
[meta] ariac 2019 task list

### ISSUE THREAD

**Issue by 130s** [130s/hut_10sqft#348]
- [x] [Registration was kind of quietly opened](https://challenge.gov/a/buzz/challenge/999/ideas/top)
- [ ] Download and check build-ability of ariac software.
- Dates of the Competition. Considering my schedule in Apr and May, submitting to qualifier will probably be the best I can do.
  - [ ]    Qualifier Begin: April 15, 2019
  - [ ]    Qualifier End: April 19, 2019
  - [ ]    Competition Testing (Finals) Period Begins: May 13, 2019
  - [ ]    Competition Testing (Finals) Period Ends: 5:00 PM, May 17, 2019
- More to come.

**Comment by 130s** [comment]
> -  [x] Download and check build-ability of ariac software.

Done with 2018 software. Docker image: [d130s/ros:kinetic-ros-core_ariac2018](https://hub.docker.com/r/d130s/ros/tags)
